### ISSUE TITLE
Header needs a line break

### ISSUE THREAD

**Issue by mlmatlock** [Lennart1978/servicemaster#19]
Interesting project!

On my 1920x1080, 96dpi monitor, this is the output:

![20240819_09h56m43s_grim](https://github.com/user-attachments/assets/1ea714bb-d4a3-4833-b78b-c6ca660f3ec0)

The A:ALL...needs its own line (or be collapsable) to not have a jumbled display.

**Comment by Lennart1978** [comment]
This looks strange. Some columns are missing somehow.
Maybe you would like to tell me what kind of terminal emulator are you using and what kind of font?
I think it has something to do with a different terminal / setting.

I have font: "Source Code Pro 10", terminal: "Kgx", maximized terminal size: 55 rows, 238 columns.
The same screen resolution: 1920x1080 96dpi.

Unfortunately, the program does not currently adapt to small windows or terminals with few columns.
That would definitely be a feature for the next update.

**Comment by Lennart1978** [comment]
I tested it with another terminal "Alacritty" and it is a bit smaller but still everything fits perfect:
![alacritty](https://github.com/user-attachments/assets/ef9c3b9e-dcaf-49f7-b05e-8b8c9872cbf4)

**Comment by mlmatlock** [comment]
Using kitty...

Forest/trees problem. Font size was too big (it's hell when you get old). 

Decreasing font size worked. Sorry for the noise...

**Comment by Tampa** [comment]
It should be possible to fetch the actual terminal size and then change the header. I tried this: https://stackoverflow.com/questions/1022957/getting-terminal-width-in-c which appears to work. :)
