### ISSUE TITLE
Major Feature Challenge

### ISSUE THREAD

**Issue by deleriux** [Lennart1978/servicemaster#2]
Depending how much free time you have- which I dont. One major way to make this a particularly novel interactive program would be to rewrite the curses part such that you:

1. Uncouple curses from using its own main loop: set `nodelay(TRUE)` again.
2. Setup your own event loop (man `sd_event_default`) 
3. Register an event handler for STDIN_FILENO, that handles any curses input (you'd pass it the `getch` call or something).
4. Setup another event handler for dbus and add it to the event loop.
5. On startup, fetch a list of all services, and register interest for various dbus properties you watch in the main title screen in each service.
6. Register on dbus for any objects (units) that get added or deleted.

What this does is effectively makes your program update the window from two input events.
1. User has typed something.
2. Systemd has changed/deleted/added a unit.

Now, whenever a status changes for a unit, dbus will notify you.
1. Capture the event and update the status of whatever service is associated with the event.
4. Refresh the curses window.

This will, in real time - update the curses window for whenever a service changes its its state.
You will also be able to do away with completely refreshing and repolling for all the services again for systemd, since dbus will send you any interesting new things your way by default.

Admittedly thats a LOT of logic, work and rewriting!

**Comment by deleriux** [comment]
Oh, and if you want to do this, you need to use the `Subscribe` method in systemd as indicated here..
https://www.freedesktop.org/wiki/Software/systemd/dbus/

This gotcha had me pulling my hair out for longer than necessary!

**Comment by Lennart1978** [comment]
First of all, thank you very much for the valuable tips and links. Indeed, it is a great challenge to rewrite the program this way. Unfortunately, I have to say that as a rather novice to maybe advanced hobby programmer, I do not feel capable of implementing this properly. I also lack the necessary basic knowledge; I would have to acquire everything little by little. It's a pity that you don't have the time for it, I'm sure you could do it. But maybe someone reading these lines feels addressed as a professional programmer as well. Any experienced programmer who feels up to such a challenge is warmly invited to participate in this project and perhaps create something great and unique. If I were to start rewriting almost everything, I would be overwhelmed with bugs and wouldn't manage at all.
